### ISSUE TITLE
Method setPosition() unstable

### ISSUE THREAD

**Issue by stonega** [alexmercerind/flutter_audio_desktop#4] opened 2020-10-23 07:32 UTC
Hi, @alexmercerind 
Thanks for the plugin, it is simple, but decent and worked well.
I find that when the duration in `setPosition()` is longer more than like 20 mins or tap fast forward many times in short time, the plugin will crash. 
Also change position take too long time and have some noisy sound.

![image](https://user-images.githubusercontent.com/2262007/96969108-86e44b80-1544-11eb-826c-0971676e0155.png)

**Comment by alexmercerind** [comment] 2020-10-24 04:34
Hello @stonega!
I'm literally 0% sure about the cause of the bug because I have used @mackron's miniaudio in this project, and made a very simple implementation over it.

I have to see what can I do.
I can't tell if my code is problematic as I always just played files of maximum about 5 minutes.

**Comment by MichealReed** [comment] 2020-12-18 22:37
@stonega this may be fixed with the latest version of miniaudio --(https://github.com/mackron/miniaudio/blob/master/miniaudio.h

Can you try dropping that into your pub cache folder for this library? 
Windows path -- User\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_audio_desktop-0.0.8\audioplayer

**Comment by stonega** [comment] 2021-01-03 13:31
@MichealReed I tested with the latest version, looks like the issue is still there. Thanks for your reply!

**Comment by alexmercerind** [comment] 2021-02-27 12:54
Hi there @stonega !

The issue is fixed in the [vnext](https://github.com/alexmercerind/flutter_audio_desktop/tree/vnext) branch.

Now, no longer whole file will be loaded into memoery, but in segments (as a stream).

I'll inform you real soon, once I get it working on Windows (will be very easy to do, as Linux implementation is already done). 

Thankyou.

**Comment by stonega** [comment] 2021-02-27 13:08
Glad to hear that, can not wait to have a test. I have switched to use
Linux these days😉

**Comment by alexmercerind** [comment] 2021-03-04 11:40
Hi there @stonega !

May you try out the plugin now on Windows or Linux?

Try running example.
There are few API changes.

I'm yet to implement playlists or queues, should be pure Dart side code.

Although, I feel there is still some delay in seeking the file. I'm not sure how better it can be now.


Please clone the repo & build the example. Let me know how it goes.
Closing for now.

**Closed as completed** 2021-03-04 11:58 UTC
Labels: bug
