### ISSUE TITLE
Playing multiple audio files

### ISSUE THREAD

**Issue by gkovac42** [alexmercerind/flutter_audio_desktop#22] opened 2020-12-18 16:00 UTC
I am forced to open another issue as my previous one was brashly closed without a proper explanation or solution, and has only left me confused. (https://github.com/alexmercerind/flutter_audio_desktop/issues/21)

How am I to play multiple audio files if I'm not supposed to call load on the same instance of AudioPlayer twice and creating multiple instances of AudioPlayer crashes the app?

**Comment by alexmercerind** [comment] 2020-12-18 16:06
Hi there @gkovac42!
Sorry for the inconvenience.
I'll take a look at the issue. In fact you are right on your point. The crash should not take place when calling load twice on an instance.
I'll try to make commit with a fix soon.
Thankyou 🍀 !

**Comment by MichealReed** [comment] 2020-12-18 16:24
Opening a new issue is not the key here, and issues aren't meant to be a help forum, they are meant to allow us to fix genuine issues with the library. Before closing your issue, I successfully tested loading many audioplayers again, and more specifically two different MP3, playing through the same and different audio devices.

I suggest that you refactor your code with suggestions from the previous issue and use the example, which also verifies that multiple players are working as intended.

Side note: multiple instances did not exist in the 0.0.7 release, you can only use multiple instances with 0.0.8.

**Closed as completed** 2020-12-18 16:46 UTC
Labels: duplicate, invalid

**Comment by MichealReed** [comment] 2020-12-18 16:49
One point of clarity, I did not mean that load can't be called twice on different instances, but more-so that you shouldn't call load more than once on the same instance. As mentioned in the previous issue, the posted code was calling play and load in the same method, so every time the play button was pressed, it would trigger a crash due to the second call to load on the same instance. Load and Play should be separate methods.
