### ISSUE TITLE
If you play long audio, the performance of the whole program will be greatly affected. I wonder if you have found this problem

### ISSUE THREAD

**Issue by JasonWULMS** [alexmercerind/flutter_audio_desktop#5] opened 2020-10-27 00:58 UTC
If you play long audio, the performance of the whole program will be greatly affected. I wonder if you have found this problem

**Comment by alexmercerind** [comment] 2021-02-27 12:54
@JasonWULMS 

The issue is fixed in the [vnext](https://github.com/alexmercerind/flutter_audio_desktop/tree/vnext) branch.

I'll inform you once, its ready.

**Comment by alexmercerind** [comment] 2021-03-04 11:40
Hi there!

Now `miniaudio_engine` is used for streaming based playback.

Issue should be fixed now.

**Closed as completed by alexmercerind** 2021-03-04 11:40 UTC
Labels: bug
